### ISSUE TITLE
How to call async functions in request handler from server to client

### ISSUE THREAD

**Issue by enp** [emlove/jsonrpc-websocket#2]
Hi,

I need to call async functions in request handler from server to client. How to do it right way?

I tried to patch jsonrpc_base/jsonrpc.py and jsonrpc_websocket/jsonrpc.py to allow to define my request handler as async, but I'm not sure if it is good solution ...

**Comment by enp** [comment]
I can just call asyncio.get_event_loop().run_until_complete(my_async_function(...)) :)

**Comment by emlove** [comment]
Looks like you've got it, but that's right. It's up to the callback to schedule any larger async functions that need to run.
