### ISSUE TITLE
How to call some remote method twice simultaneously

### ISSUE THREAD

**Issue by enp** [emlove/jsonrpc-websocket#3]
Hi,

Tried to call some remote method twice simultaneously:
```
async def call(api=None, destination=None):
    print('CALL '+destination)
    try:
        response = await api.MakeCall(num=destination)
    except:
        print(sys.exc_info())

async def main(destinations=None):
    url = 'ws://my.api/v0/api'
    api = Server(url)
    try:
        await api.ws_connect()
        tasks = []
        for destination in destinations:
            tasks.append(call(api, destination))
        await asyncio.gather(*tasks)
    except:
        print(sys.exc_info())
    finally:
        await api.close()
        await api.session.close()
```

I see CALL strings immediately but second JSON-RPC call can't start until first is completed. How can I make two calls simultaneously?

This is not server issue, I tried to call same method from different jsonrpc_websocket.Server instances and execution started simultaneously

**Comment by enp** [comment]
Tried to read jsonrpc_websocket.Server.send_message and looks like this method will run until something will be received from socket or timeout will happen - so simultaneous calls are not supported. Am I right?

**Comment by emlove** [comment]
This library is set up to support simultaneous calls, and I've pushed up a new test that confirms this is working: https://github.com/armills/jsonrpc-websocket/commit/50da885edb3a25e3c5927da31a1217e96109fbc3

When a call is made, [the request is pushed to the server on the websocket](https://github.com/armills/jsonrpc-websocket/blob/50da885edb3a25e3c5927da31a1217e96109fbc3/jsonrpc_websocket/jsonrpc.py#L37) and it [parses message responses for any open message regardless of order](https://github.com/armills/jsonrpc-websocket/blob/50da885edb3a25e3c5927da31a1217e96109fbc3/jsonrpc_websocket/jsonrpc.py#L78).

What server are you connecting to? Are you sure that server implementation doesn't synchronously handle requests on one connection? That seems like the most likely culprit to me.

**Comment by enp** [comment]
Sorry, you are right, it was server-side problem
