### ISSUE TITLE
question: how to talk to XO-server

### ISSUE THREAD

**Issue by binooetomo** [emlove/jsonrpc-websocket#8]
Dear all.
I'm a total newbie on websocket

I Have an XO-server.
I tried to talk to it using python xolib, but it have error and the last github activity is 2016. So i try to use jsonrpc-websocket.

XO have a CLI client.
i.e : xo-cli --list-subjects

I adopt the example to get the same result 

async def routine():
    server = Server(
        'ws://192.168.1.159/api/',
        auth=aiohttp.BasicAuth('myname', 'superscret'),)
    try:
        await server.ws_connect()
        await server.session.list-objects()
    finally:
        await server.close()
        await server.session.close()

asyncio.get_event_loop().run_until_complete(routine())

but I got : 
TypeError: object Method can't be used in 'await' expression

How to do it correctly?

-bino-

**Comment by emlove** [comment]
So for starters, you should be making your API calls for list-objects, on the `server` object, not on `server.session`. Additionally, dashes aren't allowed in python method names, so that might be causing problems. You should check what the actual API calls are named, since that looks like it's a CLI argument.

Can you provide the docs for the XO JSON-RPC API? Otherwise there's not much more I can help you with.

**Comment by binooetomo** [comment]
dear @emlove

You Are right.

There is a bunch of XO command, and I got it's list in json format.

I think the one that I want is :


  "xo.getAllObjects": {
    "description": "Returns all XO objects",
    "params": {
      "filter": {
        "type": "object",
        "optional": true
      },
      "limit": {
        "type": "number",
        "optional": true
      },
      "ndjson": {
        "type": "boolean",
        "optional": true
      }
    },
    "permission": ""
  },


Kindly please give me example on how to do it..
I tried to do it using a plain one-shot websocket request with payload :

        payload = {
            "method": "xo.getAllObjects",
            "params": {'filter':{'type':'host'}},
            "jsonrpc": "2.0",
            "id": uuid.uuid1().hex
        }


and pass i to a function :

    def call(self,payload,timeout=10):
        self._ws.send(json.dumps(payload))
        start_time = time.time()
        resp = None
        async while time.time() < (start_time + timeout):
            resp = json.loads(self._ws.recv())
            if ('id' not in resp) or resp['id'] != payload['id']:
                resp = None
                continue
            else:
                break
        return resp



But that method is a blocking io operation, while I want it async since I need to fetch from a abunc of host.

Just in case you need a full list of XO API command, I paste it at https://pastebin.com/D0qkWeuv

**Comment by emlove** [comment]
Nice! In that case, it should work with something like this:

```python
import asyncio
from jsonrpc_websocket import Server

async def routine():
    server = Server('ws://192.168.1.159/api/',
                    auth=aiohttp.BasicAuth('myname', 'superscret')))
    try:
        await server.ws_connect()

        result = await server.xo.getAllObjects()
        print(result)
    finally:
        await server.close()
        await server.session.close()

asyncio.get_event_loop().run_until_complete(routine())
```

**Comment by binooetomo** [comment]
Hi @emlove.
Againt I appreciate your response.

Unfortunately, the basic auth didn't work with XO-Server.
The auth have to be method call: session.signInWithPassword.
I tried that, and jsonrpc-websocket said : ClientSession have no attribute 'signInWithPassword'.

Since the basic auth didn't work, when I tried your example .. the result said 'Not enough permission'.

**Comment by emlove** [comment]
OK, so I think this is actually a problem with `jsonrpc-websocket`. We've been using `session` as a reserved attribute that references the `aiohttp.ClientSession` in use, making those API endpoints inaccessible. I've released a new version 2.0.0 which no longer exposes `session` on the Server object, and that should hopefull work for this case. So I would try this new example:


```python
import asyncio
from jsonrpc_websocket import Server

async def routine():
    server = Server('ws://192.168.1.159/api/')
    try:
        await server.ws_connect()

        result = await server.session.signInWithPassword(email='foo@example.com', password='bar')
        print(result)
    finally:
        await server.close()

asyncio.get_event_loop().run_until_complete(routine())
```

**Comment by binooetomo** [comment]
@emlove .. I realy appreciate your response.
I apologize to not response to your help very long.

Unfortunately, looks like XO use 'session' as name place of a method, while json-rpc read 'server.session' as a class.
So I got 'ClientSession object have no attribute "SigninWithPassword"'.

I think it's not problem of json-rpc, it's XO problem.

Nevermind, I got work around using aiohttp directly.

Sincerely
-bino-

**Comment by mickaelbaron** [comment]
Hi, 

To complete the solution of @emlove 

```
import json
import aiohttp
import asyncio

from jsonrpc_websocket import Server

async def routine():
    async with aiohttp.ClientSession() as client:
        server = Server('ws://XO_SERVER_IP/api/', client)

        await server.ws_connect()

        # No signIn required
        methodsInfoResult = await server.system.getMethodsInfo()
        print('\n'.join([str(e) for e in methodsInfoResult.keys()]))

        # signIn required
        result = await server.session.signIn(username='YOUR_LOGIN', password='YOUR_PASSWORD') # email attribute is working in place of username
        result = await server.xo.getAllObjects(filter={"type": "VIF"}, limit=10)

        print('[')
        print(', \n'.join([str(json.dumps(e, indent=4)) for e in result.values()]))
        print(']')

asyncio.get_event_loop().run_until_complete(routine())
```
