### ISSUE TITLE
Unable to send array type

### ISSUE THREAD

**Issue by n454149301** [emlove/jsonrpc-websocket#9]
test.py:

I want send this:

{"jsonrpc": "2.0", "method": "Api.Login", "params": [{"username": "aaa", "authority": "saaa", "password": "paaa"}]

this is my code:

`

    import asyncio
    from jsonrpc_websocket import Server

    async def routine():
        server = Server('wss://system_monitor_casbin:8808/cas/api/ws-jsonrpc/v1', verify_ssl=False)
        try:
            await server.ws_connect()
            # output: {"jsonrpc": "2.0", "method": "Api.Login", "params": {"username": "aaa", "authority": "saaa", "password": "paaa"}}
            await server.Api.Login({'username':"aaa", 'authority':'saaa', 'password':'paaa'})
            # output: {"jsonrpc": "2.0", "method": "Api.Login", "params": [[{"username": "aaa", "authority": "saaa", "password": "paaa"}]]}
            await server.Api.Login([{'username':"aaa", 'authority':'saaa', 'password':'paaa'}])

            # simple test
            # output: {"jsonrpc": "2.0", "method": "Api.Login", "params": [1]}
            await server.Api.Login(1)
            # output: {"jsonrpc": "2.0", "method": "Api.Login", "params": [[1]]}
            await server.Api.Login([1])
        finally:
            await server.close()
    asyncio.get_event_loop().run_until_complete(routine())
`

**Comment by emlove** [comment]
Looks like this was a legacy bug from `jsonrpc-requests`. Thanks for the report! I pushed out a new version `jsonrpc-websocket==3.0.0` that should fix this bug. Your first example should work now.
